### ISSUE TITLE
Colaboradores

### ISSUE THREAD

**Issue by flavioduart** [flavioduart/ex4grupo002#1]
Comentem aqui quando forem adicionados!

**Comment by caahreginaa** [comment]
Fui adicionada :dancer:

**Comment by guidoferrario** [comment]
Adicionado!

**Comment by eilins** [comment]
Adicionado também! :dart:

**Comment by RafaelRSPX** [comment]
Adicionado

**Comment by bredynilsen** [comment]
Tudo certo!

**Comment by flavioduart** [comment]
Ate aqui, quem mostrou interesse pelo trabalho, adicionado :smile:
