### ISSUE TITLE
Arquivo para revisão

### ISSUE THREAD

**Issue by RafaelRSPX** [flavioduart/ex4grupo002#11]
Implementar uma função para escrever num arquivo a palavra, a data e a nota que o usuário deu.

**Comment by eilins** [comment]
hmmm, tem de ser uma função que receba essas informações e guarde as para que se possa fazer o agendamento para o dia que ela deve re-aparecer.

**Comment by eilins** [comment]
Lembrando que a função que pega a data e hora do sistema atual já foi implementada!

**Comment by RafaelRSPX** [comment]
Fiz uma função que grava a palavra, a nota e a data. Commit: ed64ff56f8cb9846e989e3c5088576a6de371c32

**Comment by caahreginaa** [comment]
Já que a função já esta feita, irei fechar a issue.
