### ISSUE TITLE
significado no arquivo de revisão 

### ISSUE THREAD

**Issue by RafaelRSPX** [flavioduart/ex4grupo002#14]
Tava vendo o programa sem um arquivo de revisão no repositório. E gerou o seguinte arquivo: 

theory 20160420 1
nice 20160422 2
jail 20160422 3
both 20160424 4
a group of questions or problems used to find out a person's knowledge ("The students did well on the language test.")
 20160426 5
continue 20160420 1
suppress 20160422 2
yellow 20160422 3
hill 20160424 4
leak 20160426 5

A 5ª linha tá com o significado da palavra.

**Comment by caahreginaa** [comment]
Provavelmente você digitou alguma coisa errada na execução, porque eu nunca vi isso acontecer e gerei vários arquivos.

**Comment by caahreginaa** [comment]
Rodei o programa duas vezes seguidas agora e gerou o seguinte arquivo:

few 20160426 5
chemicals 20160426 5
hat 20160426 5
bill 20160422 2
population 20160426 5
mathematics 20160424 4
custom 20160426 5
intervene 20160424 4
die 20160426 5
mineral 20160426 5
nice 20160424 4
rest 20160426 5
drink 20160426 5
capital 20160426 5
substance 20160426 5
involve 20160426 5
warm 20160426 5
recover 20160426 5
aim 20160424 4
document 20160424 4

**Comment by RafaelRSPX** [comment]
Eu também to realizando alguns testes e não aconteceu. Devo ter digitado algo errado na execução mesmo.

**Comment by guidoferrario** [comment]
Eu também rodei várias vezes e não vi esse tipo de erro acontecer. Acho que realmente foi algum erro na execução.

**Comment by RafaelRSPX** [comment]
Realizei mais testes e nada de estranho aconteceu no arquivo revisao.txt. Então, acredito que apertei alguma teclar errada na execução.
