### ISSUE TITLE
Certificado

### ISSUE THREAD

**Issue by caahreginaa** [flavioduart/ex4grupo002#15]
Seria bom que começassem a função que vai imprimir o certificado quando o usuário conseguir aprender todas as palavras.

**Comment by RafaelRSPX** [comment]
Eu estou pensando na seguinte ideia: 
verifica o arquivo revisao.ex4 que vai ter todas as palavras que o usuário viu e verificar todas as notas, se todas as notas forem 5, ele imprime o certificado, mas isso só pode acontecer se o arquivo tiver as 1500 palavras.

**Comment by RafaelRSPX** [comment]
Qual seria a melhor mensagem para o certificado do usuário?

**Comment by RafaelRSPX** [comment]
Implementei um certificado simples no seguinte commit: 33d9e3e208855b375c9878f31c0636257d375a64

**Comment by caahreginaa** [comment]
Certificado mais elaborado já pode ser gerado.
