### ISSUE TITLE
Palavras novas

### ISSUE THREAD

**Issue by RafaelRSPX** [flavioduart/ex4grupo002#16]
A cada dia, pelo menos uma palavra das 10 deve ser nova certo? Como vai ser o critério? Por exemplo, se hoje é o meu 1º dia no programa e dei à 5 palavras notas para revisar amanhã, no dia seguinte, das 10 palavras, 5 vão ser as do dia anterior e 5 serão novas certo? Se sim, já temos implementamos tal ideia?

**Comment by caahreginaa** [comment]
Sera assim sim, a ideia esta para ser implementada.

**Comment by flavioduart** [comment]
A ideia é essa!! Vamos colocar no programa

**Comment by caahreginaa** [comment]
Alterei a função que era responsavel por evitar repetição das mesmas cartas por execução para exibir primeiro as atrasadas, no maximo 9, depois cartas novas (que nao estejam no arquivo de revisao) e caso nao seja possivel achar nenhuma carta que faça parte desses grupos, uma carta aletoria (que ainda não foi mostrada nessa execução) é a carta escolhida.
