### ISSUE TITLE
Arquivos .txt

### ISSUE THREAD

**Issue by caahreginaa** [flavioduart/ex4grupo002#17]
Pessoal, acho válido deixar todos os arquivos gerados no formato .txt, pois é um formato fácil de ser lido em qualquer sistema. A extensão .ex4 não é uma extensão válida.

**Comment by RafaelRSPX** [comment]
Ok. Fica melhor mesmo. Pretendo trocar

**Comment by RafaelRSPX** [comment]
Passei todas as extensões dos arquivos gerados pelo nosso programa para .txt. No seguinte commit: feaa801a3243e8029a9e93a16520f21c19745e7b
