### ISSUE TITLE
melhora no arquivo de revisão

### ISSUE THREAD

**Issue by caahreginaa** [flavioduart/ex4grupo002#18]
Pessoal, estava pensando em melhorarmos o arquivo de revisão para ao invés de salvar as palavras, a data e a media; salvar o numero da linha da palavra, a data e a media. Porque de qualquer forma utilizaremos o numero de linhas para imprimir a palavra no dia em q ela deverá ser revisada.

**Comment by RafaelRSPX** [comment]
Fica melhor. Para isso, vai ser necessário alterar o fscanf em todas as funções que utilizam o arquivo revisao.txt. Eles estão na forma fscanf(revisao, "%s %d %d", palavra, &data, &nota). Trocar para fscanf(revisao, "%d %d %d", &linha, &data, &nota).

**Comment by flavioduart** [comment]
Também acho que fica melhor sim

**Comment by RafaelRSPX** [comment]
Pensando bem, vai alterar muita coisa no código. Todas as funções que precisam ler o arquivo revisao.txt esperam uma string para recolher a palavra e não a linha da palavra. Por exemplo a função  ``` int geramedia(int nota, char *palavra)``` faz uma comparação entre a palavra que recebe e a palavra que procura no arquivo de revisão: 
``` 
int geramedia(int nota, char *palavra)
{
    FILE *p; 
    float nota2, media;
    int data, i=0, c, agendado, linha;
    char palavra2[50], string[300];

    p = fopen("revisao.txt", "r+");
    if(p==NULL) /* nao tem o arquivo */
        return 0;

    while((fscanf(p, "%s %d %f", palavra, &data, &nota2))!=EOF) <- string para palavra
    {

        if(!strcmp(palavra, palavra2)) <- comparacao de strings
        {  
            rewind(p);
            media = (nota + nota2)/2;
            agendado = agenda(media);
            for(c=0;c<i;c++)
                fgets(string, 300, p);
            fprintf(p, "%s %d %.2f\n", palavra2, agendado, media); 
            fclose(p);
            return 1;
        }
        i+=1;
    }
    fclose(p);

   return 0;
} 
```

Além da função certificado.

**Comment by flavioduart** [comment]
É, eu tentei fazer como falasse no comentário anterior, mas deu problema, então voltei pra forma normal.

**Comment by RafaelRSPX** [comment]
Alterei a função ``` void revisao(int nota, char *palavra)```  para ``` void revisao(int nota, int linha)```  para gravar a linha da palavra ao invés de gravar a palavra no arquivo revisao.txt. Falta alterar a função ``` int geramedia(int nota, char *palavra) ```

**Comment by drbeco** [comment]
É importante isso, pois se pensar em expandir, não é necessariamente obrigatório ter uma única palavra na pergunta (frente do cartão).

Aliás, o arquivo de palavras em inglês tem palavras compostas na frente do cartão! Veja por exemplo "civil rights"

Então o número da linha é mais seguro.

**Comment by RafaelRSPX** [comment]
Certo. Implementado no seguinte commit: 3b429d3d14928f485a73e803e96d5980e4cbb983
