### ISSUE TITLE
Remover os arquivos gerados

### ISSUE THREAD

**Issue by RafaelRSPX** [flavioduart/ex4grupo002#19]
Quando o usuário terminar o "curso" os arquivos: revisao.txt e contador.txt devem ser apagados quando o certificado.txt for gerado. Implementei essa ideia offline. Quando o servidor voltar ao normal, adicionarei a função. Mas quem quiser pode implementar e mandar antes, não tem problema.

**Comment by flavioduart** [comment]
Boa!! Rafael, o professor respondeu um e-mail de Bruna, e disse que enquanto o servidor estiver fora de ar pode trabalhar offline e atualizar o repositório no Github, depois, quando voltar a pegar, atualiza o servidor dando pull. Então pode adicionar a função já, que quando voltar a pegar, a gente atualiza o servidor.

**Comment by RafaelRSPX** [comment]
Implementado mostrado no commit: 82bd2201a17aedf783f90dac5238d61283284f77.
