### ISSUE TITLE
Criação de AUTHORS.

### ISSUE THREAD

**Issue by flavioduart** [flavioduart/ex4grupo002#2]
Quem criar o arquivo AUTHORS adiciona seu nome e logo após os outros editam e inserem seus respectivos nomes + e-mail. Assim que adicionarem seus nomes, comentem aqui. :ghost:

**Comment by caahreginaa** [comment]
Criei e adicionei meu nome e e-mail no AUTHORS.

**Comment by flavioduart** [comment]
Fiz o mesmo.

**Comment by eilins** [comment]
Acabei de fazer também.

**Comment by guidoferrario** [comment]
Também adicionei!

**Comment by RafaelRSPX** [comment]
Adicionei meu nome e e-mail.

**Comment by bredynilsen** [comment]
Adicionado meu nome é e-mail.

**Comment by flavioduart** [comment]
Então está feito.
