### ISSUE TITLE
revisao.txt não deleta

### ISSUE THREAD

**Issue by RafaelRSPX** [flavioduart/ex4grupo002#21]
O arquivo revisao.txt não deleta quando chama a função deleta().

**Comment by flavioduart** [comment]
Tens alguma ideia do que pode ta causando isso?

**Comment by RafaelRSPX** [comment]
Não sei. Pensava que o arquivo estava aberto enquanto a função deleta é chamada, mas não encontrei nenhum fopen sem o fclose em seguida.

**Comment by RafaelRSPX** [comment]
Resolvido.
