### ISSUE TITLE
Pergunta sem efeito

### ISSUE THREAD

**Issue by RafaelRSPX** [flavioduart/ex4grupo002#24]
No final do programa, ele pergunta se vai continuar a estudar as cartas hoje. Mas não vi muita utilidade porque no programa não faz diferença se o usuário digitar 1 para sim ou 2 para não.

**Comment by RafaelRSPX** [comment]
Devemos manter essa pergunta ou retira-la?

**Comment by guidoferrario** [comment]
Acho melhor substituí-la por uma mensagem de encerramento.

**Comment by RafaelRSPX** [comment]
Fica melhor.

**Comment by guidoferrario** [comment]
Removi a pergunta sem efeito, e adicionei uma mensagem de despedida.
