### ISSUE TITLE
Comparar data/hora.

### ISSUE THREAD

**Issue by flavioduart** [flavioduart/ex4grupo002#8]
Depois que pegar e transformar a data e hora atual, temos que relacionar com as notas das cartas que o usuário deu, e marcar no arquivo um novo dia para tal carta reaparecer.

**Comment by eilins** [comment]
Ok. A função para pegar a data e hora do sistema já foi implementada, falta agora compararmos e armazenar as datas das cartas no arquivo, algo a se pensar..

**Comment by caahreginaa** [comment]
Criei uma funçao de agendamento que já deixa salvo no arquivo o dia que a carta deverá aparecer novamente.
